package com.wenhaofan.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("article", "pkId", Article.class);
		arp.addMapping("article_category", "pkId", ArticleCategory.class);
		arp.addMapping("basic", "pkId", Basic.class);
		arp.addMapping("blogger", "pkId", Blogger.class);
		arp.addMapping("blogroll", "pkId", Blogroll.class);
		arp.addMapping("category", "pkId", Category.class);
		arp.addMapping("login_record", "pkId", LoginRecord.class);
		arp.addMapping("profiles", "pkId", Profiles.class);
		arp.addMapping("user", "pkId", User.class);
		arp.addMapping("session", "id", Session.class);	
		arp.addMapping("html_action","pkId", HtmlAction.class);
	}

	public static void createAll() {
		createDb();
		createArticle();
		createArticleCategory();
		createBasic();
		createBlogger();
		createBlogroll();
		createCategory();
		createLoginRecord();
		createProfiles();
		createUser();
		createSession();
		createHtmlAction();
	}

	public static void createDb() {
		Db.update("create DATABASE if not exists blog");
		Db.update("use blog");
	}

	public static void createArticle() {
		Db.update(
				"CREATE TABLE if not exists `article` (\r\n  `pkId` int(11) NOT NULL AUTO_INCREMENT COMMENT '文章id',\r\n  `ukTitle` varchar(30) COLLATE utf8_bin NOT NULL COMMENT '文章标题',\r\n  `content` text COLLATE utf8_bin COMMENT '文章内容',\r\n  `ukHtmlTitle` char(100) COLLATE utf8_bin NOT NULL DEFAULT '暂使用' COMMENT '文章的静态页面名称',\r\n  `gmtCreate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发表时间',\r\n  `readNum` int(11) DEFAULT '1' COMMENT '点击量',\r\n  `imageUrl` varchar(256) COLLATE utf8_bin DEFAULT NULL COMMENT '首页显示的图片的路径',\r\n  `isValid` int(1) DEFAULT '0' COMMENT '1为有效，0为已删除',\r\n  `isOriginal` int(1) DEFAULT '1' COMMENT '1为原创,0为转载',\r\n  `isTop` int(1) DEFAULT '0' COMMENT '1为置顶文章,0相反',\r\n  `gmtModified` datetime DEFAULT NULL COMMENT '最后修改时间',\r\n  PRIMARY KEY (`pkId`)\r\n) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;");
	}

	public static void createArticleCategory() {
		Db.update(
				"CREATE TABLE if not exists `article_category` (\r\n  `pkId` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',\r\n  `articleId` int(11) NOT NULL COMMENT '文章id',\r\n  `categoryId` int(11) NOT NULL COMMENT '分类id',\r\n  PRIMARY KEY (`pkId`)\r\n) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;");
	}

	public static void createBasic() {
		Db.update(
				"CREATE TABLE  if not exists `basic` (\r\n  `pkId` int(2) NOT NULL AUTO_INCREMENT,\r\n  `title` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '博客首页title',\r\n  `author` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '网站作者',\r\n  `keywords` varchar(256) CHARACTER SET utf8 DEFAULT NULL COMMENT '网页关键词',\r\n  `description` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '站点描述',\r\n  `email` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '站长邮箱',\r\n  `bottomDescription` varchar(256) CHARACTER SET utf8 DEFAULT NULL COMMENT '版权以及备案号(网站底部)',\r\n  `qiniuAk` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT '七牛云ak',\r\n  `qiniuSk` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT '七牛云sk',\r\n  `qiniuLink` varchar(80) CHARACTER SET utf8 DEFAULT NULL COMMENT '七牛云空间外链',\r\n  `qiniuBucket` varchar(80) CHARACTER SET utf8 DEFAULT NULL COMMENT '七牛bucket',\r\n  `isSaveQiniu` int(2) DEFAULT '0' COMMENT '如果为2则图片文章既保存在本地也保存在七牛云空间，为1则仅将图片文章保存至七牛云空间，0保存在本地',\r\n  `dbName` varchar(20) DEFAULT NULL,\r\n  `dbpwd` varchar(20) DEFAULT NULL,\r\n  PRIMARY KEY (`pkId`)\r\n) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;");
	}

	public static void createBlogger() {
		Db.update(
				"CREATE TABLE if not exists  `blogger` (\r\n  `pk_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',\r\n  `name` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '姓名',\r\n  `job` varchar(40) COLLATE utf8_bin NOT NULL COMMENT '职业',\r\n  `qq` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '联系qq',\r\n  `address` varchar(20) COLLATE utf8_bin NOT NULL DEFAULT 'CURREN' COMMENT '定位',\r\n  `gmtCreate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\r\n  PRIMARY KEY (`pk_id`)\r\n) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;\r\n\r\n");
	}

	public static void createBlogroll() {
		Db.update(
				"CREATE TABLE if not exists  `blogroll` (\r\n  `pkId` tinyint(4) NOT NULL AUTO_INCREMENT COMMENT '友链id',\r\n  `ukPriority` tinyint(2) NOT NULL,\r\n  `ukName` char(25) COLLATE utf8_bin NOT NULL COMMENT '友链名称',\r\n  `ukUrl` char(40) COLLATE utf8_bin NOT NULL COMMENT '友链网址',\r\n  `remark` varchar(256) COLLATE utf8_bin DEFAULT NULL COMMENT '备注信息',\r\n  PRIMARY KEY (`pkId`),\r\n  UNIQUE KEY `uk_name` (`ukName`),\r\n  UNIQUE KEY `uk_url` (`ukUrl`),\r\n  UNIQUE KEY `uk_priority` (`ukPriority`) USING BTREE\r\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;");
	}

	public static void createCategory() {
		Db.update(
				"CREATE TABLE if not exists  `category` (\r\n  `pkId` tinyint(4) NOT NULL AUTO_INCREMENT COMMENT '分类id',\r\n  `ukName` varchar(15) COLLATE utf8_bin NOT NULL COMMENT '分类名称',\r\n  `ukUrl` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '分类路径',\r\n  `ukPriority` int(20) NOT NULL COMMENT '显示优先级',\r\n  PRIMARY KEY (`pkId`),\r\n  UNIQUE KEY `uk_name` (`ukName`),\r\n  UNIQUE KEY `uk_url` (`ukUrl`),\r\n  UNIQUE KEY `uk_priority` (`ukPriority`)\r\n) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;\r\n");
	}

	public static void createLoginRecord() {
		Db.update(
				"CREATE TABLE  if not exists `login_record` (\r\n  `pkId` int(11) NOT NULL AUTO_INCREMENT COMMENT '登录记录id',\r\n  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',\r\n  `userId` int(11) NOT NULL COMMENT '用户id',\r\n  `ip` varchar(30) COLLATE utf8_bin DEFAULT '' COMMENT '登录地址',\r\n  PRIMARY KEY (`pkId`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;\r\n\r\n");
	}

	public static void createProfiles() {
		Db.update(
				"CREATE TABLE if not exists  `profiles` (\r\n  `pkId` int(2) NOT NULL DEFAULT '0',\r\n  `content` text COLLATE utf8_bin COMMENT '展示页面内容',\r\n  `pageName` varchar(40) COLLATE utf8_bin DEFAULT '' COMMENT '静态页面名称',\r\n  PRIMARY KEY (`pkId`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;\r\n");
	}

	public static void createUser() {
		Db.update(
				"CREATE TABLE if not exists  `user` (\r\n  `pkId` int(11) NOT NULL AUTO_INCREMENT COMMENT '用户id',\r\n  `name` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '用户姓名，同时作为登录账号',\r\n  `pwd` varchar(15) COLLATE utf8_bin NOT NULL COMMENT '用户登录密码',\r\n  `age` tinyint(4) NOT NULL DEFAULT '1' COMMENT '用户年龄',\r\n  `sex` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1为男，0为女',\r\n  `ukPhone` char(13) COLLATE utf8_bin NOT NULL COMMENT '用户手机号',\r\n  `ukEmail` varchar(30) COLLATE utf8_bin NOT NULL COMMENT '用户邮箱',\r\n  `level` tinyint(2) NOT NULL DEFAULT '0' COMMENT '用户等级权限,1为超级管理员,0为普通用户',\r\n  `isValid` tinyint(2) NOT NULL DEFAULT '1' COMMENT '是否生效，1为生效，0为已注销',\r\n  `ukAccount` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '登录账号',\r\n  `registerTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '用户注册时间',\r\n  PRIMARY KEY (`pkId`)\r\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;");
	}

	public static void createSession() {
		Db.update(
				"CREATE TABLE  if not exists `session` (\r\n  `id` varchar(255) CHARACTER SET latin1 DEFAULT NULL,\r\n  `expireAt` bigint(20) NOT NULL,\r\n  `userId` int(10) DEFAULT NULL\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;\r\n\r\n");
	}

	public static void createHtmlAction() {
		Db.update("CREATE TABLE if not exists `html_action` (\n" + 
				"  `pkId` int(10) unsigned NOT NULL AUTO_INCREMENT,\n" + 
				"  `path` varchar(125) DEFAULT NULL COMMENT '页面存放在服务器上的绝对路径',\n" + 
				"  `action` varchar(125) DEFAULT NULL COMMENT '页面的访问路径',\n" + 
				"  `gmtCreate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" + 
				"  PRIMARY KEY (`pkId`)\n" + 
				") ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;");
	}
}
