package com.wenhaofan.common.model;

import com.wenhaofan.common.model.base.BaseArticleCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleCategory extends BaseArticleCategory<ArticleCategory> {
	
}
