package com.wenhaofan.common.model;

import java.util.List;

import com.wenhaofan.common.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	
	/**置顶*/
	public static Integer TOP_YES=1;
	/**不置顶*/
	public static Integer TOP_NO=0;
	
	
	private List<Category> categorys;
	
	public void setCategorys(List<Category> categorys) {
		this.categorys=categorys;
	}
	
	public List<Category> getCategorys() {
		return categorys;
	}
}
