package com.wenhaofan.common.model;

import com.wenhaofan.common.model.base.BaseBasic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Basic extends BaseBasic<Basic> {
	
}
