package com.wenhaofan.common.model;

import com.wenhaofan.common.model.base.BaseBlogger;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blogger extends BaseBlogger<Blogger> {
	
}
