package com.wenhaofan.common.model;

import com.wenhaofan.common.model.base.BaseBlogroll;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blogroll extends BaseBlogroll<Blogroll> {
	
}
