package com.wenhaofan.common.model;

import com.wenhaofan.common.model.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	
}
