package com.wenhaofan.common.model;

import com.wenhaofan.common.model.base.BaseHtmlAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HtmlAction extends BaseHtmlAction<HtmlAction> {
	
	public static Integer TYPE_VIEW=0;
	public static Integer TYPE_ASSETS=1;
	
}
