package com.wenhaofan.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlogroll<M extends BaseBlogroll<M>> extends Model<M> implements IBean {

	public void setPkId(java.lang.Integer pkId) {
		set("pkId", pkId);
	}

	public java.lang.Integer getPkId() {
		return getInt("pkId");
	}

	public void setUkPriority(java.lang.Integer ukPriority) {
		set("ukPriority", ukPriority);
	}

	public java.lang.Integer getUkPriority() {
		return getInt("ukPriority");
	}

	public void setUkName(java.lang.String ukName) {
		set("ukName", ukName);
	}

	public java.lang.String getUkName() {
		return getStr("ukName");
	}

	public void setUkUrl(java.lang.String ukUrl) {
		set("ukUrl", ukUrl);
	}

	public java.lang.String getUkUrl() {
		return getStr("ukUrl");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
