package com.wenhaofan.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setPkId(java.lang.Integer pkId) {
		set("pkId", pkId);
	}

	public java.lang.Integer getPkId() {
		return getInt("pkId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}

	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setUkPhone(java.lang.String ukPhone) {
		set("ukPhone", ukPhone);
	}

	public java.lang.String getUkPhone() {
		return getStr("ukPhone");
	}

	public void setUkEmail(java.lang.String ukEmail) {
		set("ukEmail", ukEmail);
	}

	public java.lang.String getUkEmail() {
		return getStr("ukEmail");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return getInt("isValid");
	}

	public void setUkAccount(java.lang.String ukAccount) {
		set("ukAccount", ukAccount);
	}

	public java.lang.String getUkAccount() {
		return getStr("ukAccount");
	}

	public void setRegisterTime(java.util.Date registerTime) {
		set("registerTime", registerTime);
	}

	public java.util.Date getRegisterTime() {
		return get("registerTime");
	}

}
