package com.wenhaofan.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasic<M extends BaseBasic<M>> extends Model<M> implements IBean {

	public void setPkId(java.lang.Integer pkId) {
		set("pkId", pkId);
	}

	public java.lang.Integer getPkId() {
		return getInt("pkId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}

	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setBottomDescription(java.lang.String bottomDescription) {
		set("bottomDescription", bottomDescription);
	}

	public java.lang.String getBottomDescription() {
		return getStr("bottomDescription");
	}

	public void setQiniuAk(java.lang.String qiniuAk) {
		set("qiniuAk", qiniuAk);
	}

	public java.lang.String getQiniuAk() {
		return getStr("qiniuAk");
	}

	public void setQiniuSk(java.lang.String qiniuSk) {
		set("qiniuSk", qiniuSk);
	}

	public java.lang.String getQiniuSk() {
		return getStr("qiniuSk");
	}

	public void setQiniuLink(java.lang.String qiniuLink) {
		set("qiniuLink", qiniuLink);
	}

	public java.lang.String getQiniuLink() {
		return getStr("qiniuLink");
	}

	public void setQiniuBucket(java.lang.String qiniuBucket) {
		set("qiniuBucket", qiniuBucket);
	}

	public java.lang.String getQiniuBucket() {
		return getStr("qiniuBucket");
	}

	public void setIsSaveQiniu(java.lang.Integer isSaveQiniu) {
		set("isSaveQiniu", isSaveQiniu);
	}

	public java.lang.Integer getIsSaveQiniu() {
		return getInt("isSaveQiniu");
	}

	public void setDbName(java.lang.String dbName) {
		set("dbName", dbName);
	}

	public java.lang.String getDbName() {
		return getStr("dbName");
	}

	public void setDbpwd(java.lang.String dbpwd) {
		set("dbpwd", dbpwd);
	}

	public java.lang.String getDbpwd() {
		return getStr("dbpwd");
	}

}
