package com.wenhaofan.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {


	public void setPkId(java.lang.Integer pkId) {
		set("pkId", pkId);
	}

	public java.lang.Integer getPkId() {
		return getInt("pkId");
	}

	public void setUkTitle(java.lang.String ukTitle) {
		set("ukTitle", ukTitle);
	}

	public java.lang.String getUkTitle() {
		return getStr("ukTitle");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setUkHtmlTitle(java.lang.String ukHtmlTitle) {
		set("ukHtmlTitle", ukHtmlTitle);
	}

	public java.lang.String getUkHtmlTitle() {
		return getStr("ukHtmlTitle");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}
	public void setGmtModified(java.util.Date gmtModified) {
		set("gmtModified", gmtModified);
	}

	public java.util.Date GmtModified() {
		return get("gmtModified");
	}
	public void setReadNum(java.lang.Integer readNum) {
		set("readNum", readNum);
	}

	public java.lang.Integer getReadNum() {
		return getInt("readNum");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("imageUrl", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return getStr("imageUrl");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return getInt("isValid");
	}

	public void setIsOriginal(java.lang.Integer isOriginal) {
		set("isOriginal", isOriginal);
	}

	public java.lang.Integer getIsOriginal() {
		return getInt("isOriginal");
	}

	public void setIsTop(java.lang.Integer isTop) {
		set("isTop", isTop);
	}

	public java.lang.Integer getIsTop() {
		return getInt("isTop");
	}

}
